{{- if not .Values.postgresql.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opspulse.dbSecretName" . }}
  labels:
    {{- include "opspulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.postgresql.auth.secretKey }}: {{ required "Set postgresql.auth.password or postgresql.auth.existingSecret" .Values.postgresql.auth.password | quote }}
{{- end }}
